#!/bin/bash
# SMOKE EDL REGEN (external Terminal) — infinit-studio.
#
#   smoke_regen.sh <session_dir> [--steps STEPS] [--repo CHECKOUT] [--artifact-checks warn]
#   smoke_regen.sh scratch/transition_smoke/anraga/session_1776282026295
#
# Generalized from scratch/transition_smoke/regen_edl.command (PR #415). It
# WRITES a .command wrapper next to the session artifacts and opens it in
# Terminal.app — pipeline runs always go to an external Terminal so the owner
# can follow live, never to an agent's Bash tool. `arch -arm64` because
# Terminal runs x86_64 while the venv is universal2 with arm64-only numpy.
#
#   --steps           default `edl_smoothing`. Add `edl_generation` BEFORE it
#                     (`--steps edl_generation edl_smoothing`) when
#                     generation-side code changed.
#   --repo            the checkout under test (default: the main repo). Point
#                     it at a worktree to regen on a PR branch.
#   --artifact-checks `warn` downgrades the staleness preflight — expected on
#                     an older pulled copy; a smoke validates the mechanism,
#                     not a bit-exact plan.
#
# --force-regen because the artifacts already exist; --no-firebase so the
# production session doc stays untouched.
#
# Does NOT wait. It removes `<session_dir>/.regen_done` first and the wrapper
# writes the pipeline's rc there at exit — poll for that file, then read the
# tee'd log (the smoothing/generation decision lines are usually the actual
# evidence a smoke is after).
set -euo pipefail

RAW="${1:?usage: smoke_regen.sh <session_dir> [--steps STEPS] [--repo CHECKOUT] [--artifact-checks warn]}"
shift
STEPS="edl_smoothing"
REPO="/Users/llwire/src/projects/infinit-studio"
CHECKS=""
while [ $# -gt 0 ]; do
    case "$1" in
        --steps) STEPS="$2"; shift 2 ;;
        --repo) REPO="$2"; shift 2 ;;
        --artifact-checks) CHECKS="$2"; shift 2 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

SESSION_DIR="$(cd "$RAW" 2>/dev/null && pwd)" \
    || { echo "ERROR: no such session dir: $RAW" >&2; exit 2; }
# Never regen against the real session dir. A smoke works on a scratch COPY;
# /Volumes/Studio holds the masters and the owner's live artifacts.
case "$SESSION_DIR" in
    /Volumes/*) echo "ABORT: $SESSION_DIR is on /Volumes — copy the session into"\
                     "scratch/<purpose>_smoke/<partner>/<session> and regen there" >&2
                exit 2 ;;
esac
[ -f "$SESSION_DIR/session_state.json" ] \
    || echo "WARN: no session_state.json under $SESSION_DIR — is this a session dir?" >&2
[ -x "$REPO/orchestrator/venv/bin/python" ] \
    || { echo "ERROR: no venv python under $REPO/orchestrator" >&2; exit 2; }

CMD="$SESSION_DIR/regen_edl.command"
LOG="$SESSION_DIR/regen_edl.log"
DONE="$SESSION_DIR/.regen_done"
rm -f "$DONE"

cat > "$CMD" <<EOF
#!/bin/bash
# generated by cloud-e2e/scripts/smoke_regen.sh $(date -u +%Y-%m-%dT%H:%M:%SZ)
cd "$REPO/orchestrator"
${CHECKS:+export ARTIFACT_CHECKS=$CHECKS}
arch -arm64 venv/bin/python run_pipeline.py "$SESSION_DIR" \\
  --steps $STEPS --force-regen --no-firebase 2>&1 | tee "$LOG"
RC=\${PIPESTATUS[0]}
echo "\$RC" > "$DONE"
echo "── regen ($STEPS) exited \$RC — log: $LOG ──"
exec bash
EOF
chmod +x "$CMD"
open -a Terminal "$CMD"

echo "REGEN LAUNCHED in Terminal: $CMD"
echo "  repo    : $REPO"
echo "  steps   : $STEPS${CHECKS:+   (ARTIFACT_CHECKS=$CHECKS)}"
echo "  log     : $LOG"
echo "  poll    : test -f $DONE && cat $DONE   # rc 0 == regen OK"
